/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as perp from "./perp";
export type { perp };
import type * as rageTrade from "./rage-trade";
export type { rageTrade };
import type * as uniswap from "./uniswap";
export type { uniswap };
export type { IDepository } from "./IDepository";
export type { ISwapper } from "./ISwapper";
