/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PerpAccountProxy } from "./PerpAccountProxy";
export type { PerpDepository } from "./PerpDepository";
export type { PerpDepositoryStorage } from "./PerpDepositoryStorage";
